### ISSUE TITLE
Chrome now calls 'webkitCreateShadowRoot'  'createShadowRoot'

### ISSUE THREAD

**Issue by Jeff17Robbins** [bosonic/bosonic#10]
This causes a problem at line 1897 in bosonic-polyfills.js

var originalCreateShadowRoot = Element.prototype.webkitCreateShadowRoot; 

should be

var originalCreateShadowRoot = Element.prototype.createShadowRoot;

**Comment by goldoraf** [comment]
Thanks for reporting the issue! This is fixed on the master branch, I hope to release a new major version in a few days/weeks.
