### ISSUE TITLE
Gulp Plugin

### ISSUE THREAD

**Issue by indolering** [bosonic/bosonic#14]
You have a Grunt plugin, but it would be great if Gulpers could get in on the action too!    FWIW, [Angular is migrating to Gulp](http://ng-learn.org/2014/03/AngularJS-2-Status-Preview/#where_is_grunt).

**Comment by enguerran** [comment]
Why do you think it worth it to migrate from Grunt to Gulp?
I think with a good README (and the different tasks explained), there is no problem, despite of the speed, to use Grunt instead of Gulp.

**Comment by indolering** [comment]
I don't think you should switch to Gulp, I just think it would be nice to see a Gulp plugin or at least an example config.  FWIW, I tried playing around with it and it was non-trivial to get working on its own.

**Comment by goldoraf** [comment]
Hi,

I agree a Gulp plugin would be nice, it's on our wish/todolist ;)
