### ISSUE TITLE
Polymer Support?

### ISSUE THREAD

**Issue by indolering** [bosonic/bosonic#15]
I would like to use Polymer but I need to support legacy customers.  Is it possible to use Bosonic to transpile Polymer based templates and if so, how would I go about it?

**Comment by goldoraf** [comment]
Sorry for the lag, health issues have taken me away of the project for months...

What you're asking is not possible: Polymer has a lot more features than Bosonic and building a transpiler that support Polymer elements would be a daunting task. Bosonic elements will always be compatible with the Polymer platform, but if you use Polymer elements, you'll be restricted to the browsers supported by Polymer (no IE9 for example).
