### ISSUE TITLE
Unable to get property 'insertBefore' of undefined or null reference

### ISSUE THREAD

**Issue by vinhhungle** [bosonic/bosonic#17]
In the sample/index.html I replaced:
```
<script type="text/javascript" src="../node_modules/webcomponents.js/webcomponents.js"></script>
<script type="text/javascript" src="../src/runtime/register.js"></script>
```
with:
```
<script type="text/javascript" src="../dist/bosonic-platform.js"></script>
<script type="text/javascript" src="../dist/bosonic-runtime.js"></script>
```
when tested in IE9 emulation: the clock showed but there was error in console

Error: Unable to get property 'insertBefore' of undefined or null reference
File: bosonic-runtime.js, Line: 1310, Column: 5

**Comment by goldoraf** [comment]
It seems you caught another IE9 bug in the HTMLImports polyfill :/ I don't think I'll ever be able to make the runtime work with IE9 anyway. IE9 support will always require a build phase...

Thanks for reporting though, and please keep in mind things are "in flux": I'm currently "rebooting" the project, and I hope to release a new version with an updated website in the following weeks. I'll put a disclaimer in the readme.

**Comment by vinhhungle** [comment]
Thanks for your reply. I've been looking for a library that can support IE and Bosonic was the one. As mentioned on Bosonic website and Webcomponents.org IE9+ is supported so I tried to test it in the IE9. Did you mean it only works on IE10 and above?

**Comment by goldoraf** [comment]
No, the last version released on npm is compatible with IE9. This repo, and the runtime you tried to use are still in dev (& not released), and are not yet compatible with IE9.
