### ISSUE TITLE
Get back IE9 support

### ISSUE THREAD

**Issue by goldoraf** [bosonic/bosonic#20]
This probably necessitates a build task, that could be brought up from the old transpiler.

**Comment by goldoraf** [comment]
As Microsoft dropped support for IE9 on January 12th (https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support), I think it is no longer necessary to support IE9. Moreover, support would have been pretty limited anyway because IE9 lacked a lot of CSS & JS features.

**Comment by enguerran** [comment]
:+1: 

> That's one small step for a man, one giant leap for mankind - Neil Armstrong
