### ISSUE TITLE
Is there a way to disable the shadow dom support in Bosonic?

### ISSUE THREAD

**Issue by Meai** [bosonic/bosonic#28]
I think this would be a cool feature. I'm using the webcomponents-lite.js  but in Chrome Bosonic is still creating a shadow dom. 
Is there any way to make this configurable? I would like the "local" styles to simply seep into the global space in that case but still write them in the element specific style tag so that I can later move to shadowdom. 
Right now the ShadowDOM polyfill is the largest part of the polyfills, clocking in around 90KB and I dont think it's vitally necessary.

**Comment by goldoraf** [comment]
Right now this isn't possible, but as performance is my main priority, I definitely want to make Bosonic compatible with the webcomponents-lite.js polyfills. As you mentioned it, there will be CSS leaks, but it should be manageable if you're careful. I opened #29 to track this issue, we can continue the conversation there.
