### ISSUE TITLE
Transpiled CSS fails to correctly style shadowDOM nodes for browsers with native impl.

### ISSUE THREAD

**Issue by abritinthebay** [bosonic/bosonic#4]
In a browser that supports Shadow DOM (ie - Chrome) the transpiling to css will mean that all shadowDom code isn't styled.

for example: 

	<style>
		p { color: red; }
	</style>

Will get transpiled to `elementname p { color: red; }` but this won't style P in the shadowDOM at all. The following SHOULD work:

	<style>
		::shadow p { color: red; }
	</style>

But doesn't as it gets transpiled to `elementname ::shadow p { color: red; }` rather than `elementname::shadow p { color: red; }`

And obviously it wouldn't work for non-shadowDOM browsers. Polymer shims the Shadow DOM selectors it seems that Bosonic should probably transpile them (or rather - keep them correctly formatted and then duplicate the rules so non-shadowDOM browsers can access them).

Either way using Shadow DOM in Bosonic (in Shadown DOM supporting browsers) is a non-starter right now due to this.

**Comment by goldoraf** [comment]
Elements transpilation has been removed due to the project reboot. Bosonic now uses the `webcomponents.js` polyfills, so the problem should be solved.
